### PR TITLE
Laytec Improvements

### PR DESCRIPTION
**Pull request by aalbino2**

### CODE REVIEW

**Comment by aalbino2** [comment]
@budschi I will set you as a reviewer later on.

**Comment by aalbino2** [comment]
@hampusnasstrom I opened this PR to work a bit on LAyTec.

I would like to move all the parsing part from the normalize function (in the schema.py) to the parse function (in the parser.py)

Before going on it, do you also confirm that this is worth doing? Otherwise the parsing would happen everytime the archive is changed from GUI and saved again.

I will leave things like plotting in the normalize function, though.

**Comment by hampusnasstrom** [comment]
> @hampusnasstrom I opened this PR to work a bit on LAyTec.
> 
> I would like to move all the parsing part from the normalize function (in the schema.py) to the parse function (in the parser.py)
> 
> Before going on it, do you also confirm that this is worth doing? Otherwise the parsing would happen everytime the archive is changed from GUI and saved again.
> 
> I will leave things like plotting in the normalize function, though.

@aalbino2 this does not align with what we decided together with @Pepe-Marquez, @ka-sarthak, and @budschi for the general measurements. You can look how we do it in the xrd plugin for an example. I would suggest discussing with Sarthak and Sebastian before doing a lot of work.

**Comment by aalbino2** [comment]
I got informed by @ka-sarthak about the machinery. The reader and writer part of the parser make sense, it is derived from the nexus readers we have from area B

we will meet to discuss all together whether this will need to be in the schema.py or parser.py file

**Pull request merged**
